import { DelegatedTestSlotRow } from '../delegated-examiner-bookings-repository';

export const mockDelegatedBookingRows: DelegatedTestSlotRow[] = [
  {
    app_id: 41234567,
    slot_id: 1,
    start_time: null,
    vehicle_type_code: 'B',
    vehicle_slot_type_code: 15,
    booking_id: 24306179,
    driver_number: 'HOMER146246AJ9AG',
    individual_id: 1,
    first_forename: 'Homer',
    family_name: 'Simpson',
    test_category_ref: 'B',
    booking_seq: 2,
    check_digit: 1,
    tc_id: 1,
    tc_name: 'test centre',
    tc_cost_centre_code: 'cost code',
    date_of_birth: new Date('1990-12-15'),
    staff_number: '1234567',
  },
  {
    app_id: 41234568,
    slot_id: 2,
    start_time: null,
    vehicle_type_code: 'C',
    vehicle_slot_type_code: 14,
    booking_id: 24306180,
    driver_number: 'LISA9146246AJ9AG',
    individual_id: 1,
    first_forename: 'Lisa',
    family_name: 'Simpson',
    test_category_ref: 'C',
    booking_seq: 3,
    check_digit: 4,
    tc_id: 1,
    tc_name: 'test centre',
    tc_cost_centre_code: 'cost code',
    date_of_birth: new Date('1906-02-05'),
    staff_number: '4583912',
  },
  {
    app_id: 41234569,
    slot_id: 3,
    start_time: null,
    vehicle_type_code: 'D',
    vehicle_slot_type_code: 4,
    booking_id: 24306181,
    driver_number: 'BART9146246AJ9AG',
    individual_id: 1,
    first_forename: 'Bart',
    family_name: 'Simpson',
    test_category_ref: 'D',
    booking_seq: 5,
    check_digit: 3,
    tc_id: 1,
    tc_name: 'test centre',
    tc_cost_centre_code: 'cost code',
    date_of_birth: new Date('1988-05-25'),
    staff_number: '2468053',
  },
  {
    app_id: 41234561,
    slot_id: 4,
    start_time: null,
    vehicle_type_code: 'B',
    vehicle_slot_type_code: 15,
    booking_id: 24306182,
    driver_number: 'MARGE146246AJ9AG',
    individual_id: 1,
    first_forename: 'Marge',
    family_name: 'Simpson',
    test_category_ref: 'B',
    booking_seq: 6,
    check_digit: 4,
    tc_id: 1,
    tc_name: 'test centre',
    tc_cost_centre_code: 'cost code',
    date_of_birth: new Date('1992-01-20'),
    staff_number: '9865321',
  },
];
