import { mapRow } from '../test-slot-row-mapper';

describe('TestSlot Row Mapper', () => {

  it('should map a TestSlotRow to an ExaminerTestSlot', () => {
    const result = mapRow({
      slot_id: 1,
      start_time: new Date('2019-02-12 08:20:00'),
      minutes: 57,
      vehicle_slot_type: 'B57Minutes',
      tc_id: 3,
      tc_cost_centre_code: 'costcentre',
      tc_name: 'testcentre',
      individual_id: 4,
      programme_date: '2019-02-12 00:00:00',
      booking_id: 5,
      app_id: 6,
      booking_seq: 7,
      check_digit: 8,
      welsh_test_ind: 1,
      ext_req_ind: 0,
      progressive_access: 0,
      meeting_place: 'meeting',
      special_needs: 'special',
      ent_check_ind: 1,
      cab_seat_count: 9,
      passenger_seat_count: 10,
      height_metres: 11,
      length_metres: 12,
      width_metres: 13,
      vehicle_category: 'vehcat',
      gearbox_type: 'Manual',
      candidate_id: 14,
      candidate_title: 'Mr',
      candidate_first_name: 'Joe',
      candidate_second_name: 'Adam',
      candidate_third_name: 'Kyle',
      candidate_surname: 'Bloggs',
      candidate_driver_number: '16',
      cand_primary_tel: '0011',
      cand_secondary_tel: '2233',
      cand_mobile_tel: '4455',
      cand_email: 'joe.bloggs@example.com',
      candidate_addr_line1: 'addr1',
      candidate_addr_line2: 'addr2',
      candidate_addr_line3: 'addr3',
      candidate_addr_line4: 'addr4',
      candidate_addr_line5: 'addr5',
      candidate_post_code: 'abc123',
      candidate_prn: 17,
      prev_attempts: 18,
      business_id: 18,
      business_name: 'business',
      business_addr_line1: 'ba1',
      business_addr_line2: 'ba2',
      business_addr_line3: 'ba3',
      business_addr_line4: 'ba4',
      business_addr_line5: 'ba5',
      business_post_code: 'bpc',
      business_telephone: '6677',
      cancel_initiator: 'DSA,Act of nature',
    });
    expect(result).toEqual(
      {
        examinerId: 4,
        testSlot: {
          booking: {
            application: {
              applicationId: 6,
              bookingSequence: 7,
              checkDigits: 8,
              welshTest: true,
              extendedTest: false,
              meetingPlace: 'meeting',
              progressiveAccess: false,
              specialNeeds: 'special',
              entitlementCheck: true,
              vehicleSeats: 19,
              vehicleHeight: 11,
              vehicleWidth: 13,
              vehicleLength: 12,
              testCategory: 'vehcat',
              vehicleGearbox: 'Manual',
            },
            business: {
              businessAddress: {
                addressLine1: 'ba1',
                addressLine2: 'ba2',
                addressLine3: 'ba3',
                addressLine4: 'ba4',
                addressLine5: 'ba5',
                postcode: 'bpc',
              },
              businessId: 18,
              businessName: 'business',
              telephone: '6677',
            },
            candidate: {
              candidateAddress: {
                addressLine1: 'addr1',
                addressLine2: 'addr2',
                addressLine3: 'addr3',
                addressLine4: 'addr4',
                addressLine5: 'addr5',
                postcode: 'abc123',
              },
              candidateId: 14,
              candidateName: {
                firstName: 'Joe',
                secondName: 'Adam',
                thirdName: 'Kyle',
                lastName: 'Bloggs',
                title: 'Mr',
              },
              driverNumber: '16',
              emailAddress: 'joe.bloggs@example.com',
              mobileTelephone: '4455',
              primaryTelephone: '0011',
              secondaryTelephone: '2233',
              previousADITests: 18,
              prn: 17,
            },
            previousCancellation: [
              'DSA',
              'Act of nature',
            ],
          },
          slotDetail: {
            duration: 57,
            slotId: 1,
            start: '2019-02-12T08:20:00+00:00',
          },
          testCentre: {
            centreId: 3,
            centreName: 'testcentre',
            costCode: 'costcentre',
          },
          vehicleSlotType: 'B57Minutes',
        },
      },
    );
  });
});
